spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: "${project.artifactId}-sa"
      containers:
        - name: ${project.artifactId}
          resources:
            limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: SPRING_PROFILES_ACTIVE
            value: ${spring.profiles.active}
  triggers:
  - type: ConfigChange
  - imageChangeParams:
     automatic: true
     containerNames:
     - ${project.artifactId}
     from:
       kind: ImageStreamTag
       name: ${project.artifactId}:latest